### ISSUE TITLE
Maximum number of neighbours in the imdb tutorial

### ISSUE THREAD

**Issue by Milania1** [tensorflow/neural-structured-learning#4]
There is an inconsistency regarding the maximum number of neighbours to use in the tutorial. In the `Augment training data with graph neighbors` section, a maximum of 1 neighbour is mentioned. However, in the following run of the `pack_nbrs` tool the parameter `--max_nbrs=3` is used. The `HParams` object later specifies `self.num_neighbors = 2`.

If I had to guess, I would say it should be 2 neighbours everywhere. Please note that this also changes the output of the `pack_nbrs` tool.

Thanks for sharing this library!

**Comment by arjung** [comment]
Thanks @Milania1 for running through our tutorial and for reporting the inconsistency! The only typo is in the text of the `Augment training data with graph neighbors` section (it should be 3 instead of 1). I will fix this shortly.

The value of HParams.num_neighbors can be any value in the inclusive interval [0,3]. This is because the input training data for graph-based NSL was generated (by the `pack_nbrs` program) to include a maximum of 3 neighbors per sample. So, when training a model, we may choose to use fewer neighbors per sample. The IMDB tutorial illustrates using 2 neighbors per sample but you may also use 0, 1, or 3 neighbors per sample. Hope this clarifies your question.

**Comment by arjung** [comment]
Fixed in https://github.com/tensorflow/neural-structured-learning/commit/6cb6b22174ba5f5d6b621443eb2b147831be320d.
