### ISSUE TITLE
Potential example tutorial for Adversarial Learning

### ISSUE THREAD

**Issue by dipanjanS** [tensorflow/neural-structured-learning#65]
Hi @arjung creating this issue based on our conversation earlier. Open to thoughts on if this might be a valid example to also showcase besides the existing ones we have here on NSL. Folks did seem to like this one and we plan to also showcase this and some more (maybe on NLP too) in some upcoming conferences\events. This can BTW be edited and modified based on what might be appropriate \ relevant to make it presentable as per Google \ TF standards based on your insights.

Following is a notebook showcasing applying adversarial attacks (FGSM) on the FashionMNIST benchmark dataset leveraging a pre-trained model (VGG) and also how we used NSL to create a robust model and did some benchmarking on the test dataset after perturbations. This was given as a talk in the TensorFlow User Group India Summit 2020 which happened recently.

- [**Colab Notebook Tutorial**](https://colab.research.google.com/github/dipanjanS/adversarial_learning_tfug2020/blob/master/tutorials/Adversarial_Learning_Robust_Vision_Models.ipynb)

- [**GitHub Repo**](https://github.com/dipanjanS/adversarial_learning_tfug2020)

- [**TFUG 2020 Session Video**](https://www.youtube.com/watch?v=qi1cVGTa3sg&feature=youtu.be&t=2569&ab_channel=TFUGIndiaSummit)

**Comment by arjung** [comment]
Thanks for reaching out, @dipanjanS! We are definitely excited about your example and presentation. 

Re: the presentation/video, we are planning to create a page in our GitHub repo to highlight talks, videos, presentations on NSL. Once we do that, we can add a link to the YouTube video you just shared.

Re: the example tutorial, we'd definitely be happy to accept this as a contribution to our repo. We think that a good initial destination for this would be `neural_structured_learning/examples/notebooks`. Feel free to submit it as a PR and we can review it and suggest changes/comments so that it adheres to some of our standards.

Let me know if this plan sounds good to you.

**Comment by dipanjanS** [comment]
Sounds great thanks! I'll link the PR here once I create it

**Comment by dipanjanS** [comment]
@arjung added details in  #67

**Comment by arjung** [comment]
Merged in https://github.com/tensorflow/neural-structured-learning/pull/76. Closing this issue.
